config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'account', to: 'dashboards#account'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :cars, only: [:new, :index, :create, :show] do
     resources :bookings, only: [:new, :create, :index, :show]
  end

  resources :reviews, only: [:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :car
  belongs_to :user

  has_one :review

  validates :start_date, :end_date, presence: true
  validate :end_date_after_start_date
  validate :start_date_today

  private

  def end_date_after_start_date
    return if end_date.blank? || start_date.blank?

    if end_date < start_date
      errors.add(:end_date, "must be after the start date")
    end
  end

  def start_date_today
    return if end_date.blank? || start_date.blank?

    if end_date == Date.today
      errors.add(:start_date, "cannot be end date")
    end
  end

end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :reviews, through: :bookings
  has_one_attached :photo

  CATEGORIES = ["German", "French", "British", "Italian", "American"]
  validates :brand, :model, :year, :price_day, presence: true
  validates :category, inclusion: { in: CATEGORIES }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking
  validates :rating, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cars, dependent: :destroy
  has_many :bookings, dependent: :destroy
  validates :first_name, :last_name, presence: true
  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def new
    @car = Car.find(params[:car_id])
    @booking = Booking.new
  end

  def create
    @car = Car.find(params[:car_id])
    @booking = Booking.new(bookings_params)
    @booking.car = @car
    @booking.user = current_user
    if @booking.save
      redirect_to car_path(@car)
      @booking.status = "Pending"
    else
      render :new
    end
  end

  def index
    @bookings = Booking.all
  end

  def show
    @booking = Booking.find(params[:id])
  end

  private

  def bookings_params
    params.require(:booking).permit(:status, :start_date, :end_date)
  end

end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
    @cars = Car.all
  end

  def new
    @car = Car.new
  end

  def create
    @car = Car.new(car_params)
    @car.user = current_user
    if @car.save!
      redirect_to car_path(@car)
    else
      render :new
    end
  end

  def show
    @car = Car.find(params[:id])
    @cars = Car.all
  end

  private

  def car_params
    params.require(:car).permit(:brand, :model, :year, :price_day, :description, :category, :photo)
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def account
    @review = Review.new
    @my_bookings = Booking.where(user: current_user)
    # @my_cars_bookings = User.id.where(current_user.cars.bookings)
    @all_bookings = Booking.all
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
    @cars = Car.all
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @review = Review.new(review_params)
    if @review.save!
      redirect_to account_path
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:booking_id, :comment, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<div class='container col-4'>
  <h1 style="color: #064124; font-size: 40px; margin: 40px 0px;"><strong>Book the: <%= @car.model %> </strong> </h1>
<%= simple_form_for [@car, @booking] do |f| %>
  <%= f.input :start_date, as: :date, html5: true %>
  <%= f.input :end_date, as: :date, html5: true %>
  <div class="btn btn-sm">
  <%= f.button :submit%>
  </div>
<% end %>
  <div>
    <%= link_to 'Go back', car_path(@car) %>
  </div>
</div>

app/views/cars/index.html.erb
<div class="px-4">
  <div class="cards">
    <% @cars.each do |car| %>
      <div class="card-car">
        <div>
          <%= link_to car_path(car) do %>
          <%= cl_image_tag car.photo.key, class: "card-car-img" %>
          <% end %>
        </div>

        <div class="card-car-infos">
          <div>
            <h6><%= car.year %> <%= car.brand %> <%= car.model %></h6>
            <% 5.times do %>
             <i class="far fa-star"></i>
            <% end %>
          </div>
          <p class="card-car-pricing"><strong><%= car.price_day.to_i %>€</strong>/Day</p>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/cars/new.html.erb
<div class='container col-4'>
  <h1 style="color: #064124; font-size: 40px; margin: 40px 0px;"><strong>Add your classic car</strong></h1>
  <%= simple_form_for @car do |f| %>
    <%= f.input :brand %>
    <%= f.input :model %>
    <%= f.input :year %>
    <%= f.input :price_day %>
    <%= f.input :category, collection: Car::CATEGORIES   %>
    <%= f.input :description, as: :text %>
    <%= f.input :photo, as: :file %>
    <%= f.button :submit, class:"create-btn"  %>
  <% end %>
</div>

app/views/cars/show.html.erb
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <% @sum = 0 %>
  <% @count = 0 %>
  <% @avg = 0 %>
  <% @car.bookings.each do |booking| %>
  <% @count += 1 %>
  <% @sum += booking&.review&.rating.to_i %>
  <% @avg = @sum / @count %>
  <% end %>

  <div class="car-overview mb-2">
    <h1 class="title" style="margin-top: 40px; margin-bottom: 40px; font-size: 60px;">
      <%= @car.year %> <%= @car.brand %> <%= @car.model %>
    </h1>
  </div>
  <div class="img-cont mb-4" style="background-image: url('<%= cl_image_path(@car.photo.key) %>');">
   <!--  <a href="#jump">linked text</a> -->
    <a href="#jump" style="font-size: 85px; margin-top: 630px; color: #065224;"><i class="fas fa-angle-double-down" style="transition-delay: 2s;"></i></a>
  </div>
<div class="px-5 pt-5">
  <div class="w-75 mr-auto ml-auto">


    <div class="price-rating mb-2" style="display: flex; justify-content: space-between;" >
      <h2 class="price" id='jump'style="font-size: 20px; color: #064125; margin-top: 10px; font-weight: bold">Price per day: <%= (@car.price_day).to_i %>€</h2>
      <%= link_to "Book now", new_car_booking_path(@car), class:"btnprimary" %>
      <h2 class="rating" style="font-size: 20px; color: #064125; margin-top: 10px; font-weight: bold">
        <% if @count > 0 %>
          <span class="heading" style="margin-left: 20px">User Rating : </span>
              <% 5.times do |i|  %>
                <span class="fa fa-star <%= "checked" if i + 1 <= @avg  %>"></span>
              <% end %>
        <% else %>
        Rating: <i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i> </h2>
        <% end %>
    </div>
    <br>
    <div style="display: flex;">
      <p><%= @car.availability %></p>
      <p>Currently available</p>
    </div>


    <div class="car_description" >
      <p style="text-align: justify; margin-bottom: 80px"><%= @car.description %></p>
    </div>

    <div style="text-align:  left">
      <h3>Recent Reviews</h3>

      <% @car.bookings.each do |booking| %>
        <% if booking.review %>
          <h6><%= booking.user.first_name %> <%= booking.user.last_name %> - <%= booking.review.comment %>
            <span class="heading" style="margin-left: 20px">User Rating : </span>
            <% 5.times do |i|  %>
              <span class="fa fa-star <%= "checked" if i + 1 <= booking.review.rating  %>"></span>
            <% end %>
         </h6>
        <% end %>

      <% end %>
    </div>



    <div class='recommendations'>
      <div class="change-show" style="text-align:center;">
        <h2 style="font-size: px">Our Recommendations</h2>
      </div>
      <div class="px-4-show">
      <div class="cards-show">
        <% @cars[0..3].map do |car| %>
          <div class="card-car-show">
            <div>
              <%= link_to car_path(car) do %>
              <%= cl_image_tag car.photo.key, class: "card-car-img-show" %>
              <% end %>
            </div>

            <div class="card-car-infos-show">
              <div>
                <h6><%= car.year %> <%= car.brand %> <%= car.model %></h6>
                <% 5.times do %>
                 <i class="far fa-star"></i>
                <% end %>
              </div>
              <p class="card-car-pricing-show"><strong>£<%= car.price_day %></strong>/Day</p>
            </div>
          </div>
        <% end %>
      </div>
      </div>
    </div>










  </div>
</div>

app/views/dashboards/account.html.erb
<ul class="nav nav-tabs" id="myTab" role="tablist">
  <li class="nav-item">
    <a class="nav-link active" data-toggle="tab" href="#mybookings">My Bookings</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" data-toggle="tab" href="#requests">Requests for your cars</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" data-toggle="tab" href="#settings">Your car settings</a>
  </li>
</ul>

<div class="tab-content">



  <div id="mybookings" class="tab-pane active">
    <% @my_bookings.each do |booking| %>
      <div class="car-booking">
          <%= cl_image_tag booking.car.photo.key, id: "car-img"%>
        <div class="car-booking-infos">
          <h4><%= booking.car.brand %> <%= booking.car.model %></h4>
          <h6><strong><%= booking.start_date %></strong> until <strong><%= booking.end_date %></strong> </h6>
          <h6>Total period : <%= (booking.end_date.to_date - booking.start_date.to_date).to_i  %> days.</h6>
          <h6>Price : <%= (((booking.end_date.to_date - booking.start_date.to_date).to_i ) * booking.car.price_day).to_i %>€ </h6>
        </div>
        <div style="margin-left :25px ">
          <h6><strong>Booking status : <i class="far fa-clock"></i> <%= booking.status %> </strong> </h6>
        </div>
        <div style="margin-left: 500px">
          <% if booking.review.nil? %>
          <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#booking-<%= booking.id %>">
            Review this booking
          </button>
          <% else %>
            <p>Review already submitted</p>
          <% end %>
        </div>
      </div>



      <div class="modal fade" id="booking-<%= booking.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Review</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <%= simple_form_for (@review) do |f| %>
                <%= f.hidden_field :booking_id, value: booking.id %>
                <%= f.input :comment %>
                <%= f.input :rating, collection: 1..5 %>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <%= f.submit "Review" %>
            </div>
            <% end %>
          </div>
        </div>
      </div>

    <% end %>
  </div>



  <div id="requests" class="tab-pane">
    <% @all_bookings.each do |booking| %>
      <% if current_user == booking.car.user %>
        <div class="car-booking">
          <%= cl_image_tag booking.car.photo.key, id: "car-img"%>
          <div class="car-booking-infos">
            <h4><%= booking.car.brand %> <%= booking.car.model %></h4>
            <h6><strong><%= booking.start_date %></strong> until <strong><%= booking.end_date %></strong> </h6>
            <h6>Total period : <%= (booking.end_date.to_date - booking.start_date.to_date).to_i  %> days.</h6>
            <h6>Price : <%= (((booking.end_date.to_date - booking.start_date.to_date).to_i ) * booking.car.price_day).to_i %>€ </h6>
          </div>
          <div style="margin-left :25px ">
            <h6><strong>DO YOU ACCEPT THIS BOOKING ?  </strong> </h6>
            <button class="btn btn-outline-success">YES</button>
            <button class="btn btn-outline-danger">NO</button>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>

  <div id="settings" class="tab-pane">
  </div>



</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Classics</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Work+Sans:ital,wght@1,300&display=swap" rel="stylesheet">


  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
      <%= yield %>


  <footer>
    <%= render 'shared/footer' %>
  </footer>


  </body>
</html>

app/views/pages/home.html.erb
<div class='wrapper col-12'>
    <h1>Welcome to <strong><i>Classics</i></strong></h1>
    <h2>The drivers club for vintage car enthusiasts</h2>
    <div class='button-wrapper'>
      <%= link_to "Our Classics", cars_path , class: "all-btn"%>
    </div>
</div>

<div class='center center--list-info' style='display: flex; justify-content: space-around; padding: 100px'>
    <div class='list-info__section' style='background-color: #E9ECEF; text-align: center; padding: 15px' >
      <h3 class='list-info__title' style='font-size: 30px'>For drivers, by drivers.</h3>
      <div class='list-info__txt cke-list'>
        <p style='text-align: justify; font-weight: 100'>
          It's the best way to drive. With Classics, you don't have to buy or lease an oldtimer; just rent one. So whether you need to rent a car for 2 minutes or two weeks, you can get going with just one click. Find us in Barcelona, and more – for all your plans, big and small. What else?
        </p>
      </div>
    </div>
    <div class='list-info__section' style='background-color: #E9ECEF; text-align: center; padding: 15px'>
      <h3 class='list-info__title' style='font-size: 30px'>Dare to push our cars to the limit.</h3>
      <div class='list-info__txt cke-list'>
        <p style='text-align: justify; font-weight: 100'>
          Undertaking Classics is the vehicle rental organisation you can trust. With only the spiffiest cars, we're eager to assist you in tracking down the right rental vehicle. We generally put the client first, which is the reason you can anticipate modest rental vehicles as well as five-star administration. So regardless of whether you're on vacation, on your own or just want to unwind from daily stress... - visit us at one of our rental vehicle stations for an individual discussion.
        </p>
      </div>
    </div>
    <div class='list-info__section' style='background-color: #E9ECEF; text-align: center; padding: 15px'>
      <h3 class='list-info__title' style='font-size: 30px'>We've got you covered in case of total damage.</h3>
      <div class='list-info__txt cke-list'>
        <p style='text-align: justify; font-weight: 100'>
          Here some random text that no one in his right mind would read before leaving a 10m car to a stranger.
          Here some random text that no one in his right mind would read before leaving a 10m car to a stranger.
          Here some random text that no one in his right mind would read before leaving a 10m car to a stranger.
        </p>
      </div>
    </div>
</div>
<div class='favourites'>
  <div class="change" style="text-align:center;">
    <h2>Our members' most driven cars</h2>
  </div>
  <div class="px-4-home">
  <div class="cards-home">
    <% @cars[0..3].each do |car| %>
      <div class="card-car-home">
        <div>
          <%= link_to car_path(car) do %>
          <%= cl_image_tag car.photo.key, class: "card-car-img-home" %>
          <% end %>
        </div>

        <div class="card-car-infos-home">
          <div>
            <h6><%= car.year %> <%= car.brand %> <%= car.model %></h6>
            <% 5.times do %>
             <i class="far fa-star"></i>
            <% end %>
          </div>
          <p class="card-car-pricing-home"><strong><%= car.price_day.to_i %>€</strong>/Day</p>
        </div>
      </div>
    <% end %>
  </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer-clean">
  <footer class="mb-0">
      <div class="footer_container">
          <div class="container" style="min-height: 5vh;">
            <div class="row justify-content-center">
                <div class="col-sm-4 col-md-3 item">
                    <h3 class="services">Services</h3>
                    <ul>
                        <li>Web design</li>
                        <li>Development</li>
                        <li>Hosting</li>
                    </ul>
                </div>
                <div class="col-sm-4 col-md-3 item">
                    <h3 class="about">About</h3>
                    <ul>
                        <li>Company</li>
                        <li>Team</li>
                        <li>Legacy</li>
                    </ul>
                </div>
                <div class="col-sm-4 col-md-3 item">
                    <h3 class="careers">Careers</h3>
                    <ul>
                        <li>Job openings</li>
                        <li>Employee success</li>
                        <li>Benefits</li>
                    </ul>
                </div>
                  <h6 class="copyright">Classics © 2021</h6>
            </div>
          </div>
      </div>
  </footer>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="navbar logo">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= cl_image_tag "gratis-png-coche-clasico-logo-ac-cobra-vehiculo-de-motor-coche-clasico_2_lweuv0.png", size: '120x0' %>
      <% end %>
  </div>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="d-flex" style="padding-right: 120px; color: white;">
    <% if user_signed_in? %>
      <h6 class="nav-item mr-3" >
        <a class=" btn btn-outline-secondary nav-link" style="border-radius: 5px;" href="<%= new_car_path %>">
          LIST YOUR CAR
        </a>
      </h6>
    <% end %>
  </div>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <i class="fas fa-portrait avatar" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></i>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "My account", account_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>